package br.com.lemontech.selfbooking.wsselfbooking.services;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-01-29T19:44:57.990-03:00
 * Generated source version: 4.0.3
 *
 */
@WebService(targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", name = "WsSelfBooking")
@XmlSeeAlso({br.com.lemontech.selfbooking.wsselfbooking.beans.carro.ObjectFactory.class, br.com.lemontech.selfbooking.wsselfbooking.beans.solicitacaotolistarparametrizacaocentrodecusto.ObjectFactory.class, br.com.lemontech.selfbooking.wsselfbooking.beans.solicitacaotolistarcentrodecusto.ObjectFactory.class, br.com.lemontech.selfbooking.wsselfbooking.beans.seguro.ObjectFactory.class, br.com.lemontech.selfbooking.wsselfbooking.beans.traslado.ObjectFactory.class, br.com.lemontech.selfbooking.wsselfbooking.beans.ObjectFactory.class, br.com.lemontech.selfbooking.wsselfbooking.services.response.ObjectFactory.class, br.com.lemontech.selfbooking.wsselfbooking.beans.rodoviario.ObjectFactory.class, br.com.lemontech.selfbooking.wsselfbooking.beans.hotel.ObjectFactory.class, br.com.lemontech.selfbooking.wsselfbooking.beans.expense.ObjectFactory.class, br.com.lemontech.selfbooking.wsselfbooking.beans.types.ObjectFactory.class, br.com.lemontech.selfbooking.wsselfbooking.beans.fornecedor.ObjectFactory.class, br.com.lemontech.selfbooking.wsselfbooking.beans.centrodecustotolistarcentrodecusto.ObjectFactory.class, br.com.lemontech.selfbooking.wsselfbooking.beans.outro.ObjectFactory.class, br.com.lemontech.selfbooking.wsselfbooking.beans.aereo.ObjectFactory.class, br.com.lemontech.selfbooking.wsselfbooking.services.request.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface WsSelfBooking {

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarParametrizacaoViajanteRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarParametrizacaoViajanteResponse")
    @WebResult(name = "cadastrarParametrizacaoViajanteResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarParametrizacaoViajanteResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.CadastrarParametrizacaoViajanteResponse cadastrarParametrizacaoViajante(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "cadastrarParametrizacaoViajante", name = "cadastrarParametrizacaoViajante", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.CadastrarParametrizacaoViajanteRequest cadastrarParametrizacaoViajante
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarControleClienteRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarControleClienteResponse")
    @WebResult(name = "cadastrarControleClienteResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarControleClienteResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.CadastrarControleClienteResponse cadastrarControleCliente(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "cadastrarControleCliente", name = "cadastrarControleCliente", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.CadastrarControleClienteRequest cadastrarControleCliente
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/alterarStatusTarifarioRequest", output = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/alterarStatusTarifarioResponse")
    @WebResult(name = "alterarStatusTarifarioResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "alterarStatusTarifarioResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.AlterarStatusTarifarioResponse alterarStatusTarifario(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "alterarStatusTarifario", name = "alterarStatusTarifario", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.AlterarStatusTarifarioRequest alterarStatusTarifario
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/alterarStatusSubCentroDeCustoRequest", output = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/alterarStatusSubCentroDeCustoResponse")
    @WebResult(name = "alterarStatusSubCentroDeCustoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "alterarStatusSubCentroDeCustoResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.AlterarStatusSubCentroDeCustoResponse alterarStatusSubCentroDeCusto(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "alterarStatusSubCentroDeCusto", name = "alterarStatusSubCentroDeCusto", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.AlterarStatusSubCentroDeCustoRequest alterarStatusSubCentroDeCusto
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/pesquisarConciliacaoCartaoRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/pesquisarConciliacaoCartaoResponse")
    @WebResult(name = "pesquisarConciliacaoCartaoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "pesquisarConciliacaoCartaoResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.PesquisarConciliacaoCartaoResponse pesquisarConciliacaoCartao(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "pesquisarConciliacaoCartao", name = "pesquisarConciliacaoCartao", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.PesquisarConciliacaoCartaoRequest pesquisarConciliacaoCartao
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarUnidadeNegocioRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarUnidadeNegocioResponse")
    @WebResult(name = "cadastrarUnidadeNegocioResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarUnidadeNegocioResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.CadastrarUnidadeNegocioResponse cadastrarUnidadeNegocio(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "cadastrarUnidadeNegocio", name = "cadastrarUnidadeNegocio", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.CadastrarUnidadeNegocioRequest cadastrarUnidadeNegocio
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/cadastrarTarifarioRequest", output = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/cadastrarTarifarioResponse")
    @WebResult(name = "cadastrarTarifarioResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarTarifarioResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.CadastrarTarifarioResponse cadastrarTarifario(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "cadastrarTarifario", name = "cadastrarTarifario", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.CadastrarTarifarioRequest cadastrarTarifario
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/finalizarSolicitacaoRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/finalizarSolicitacaoResponse")
    @WebResult(name = "finalizarSolicitacaoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "finalizarSolicitacaoResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.FinalizarSolicitacaoResponse finalizarSolicitacao(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "finalizarSolicitacao", name = "finalizarSolicitacao", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.FinalizarSolicitacaoRequest finalizarSolicitacao
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarRegionalRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarRegionalResponse")
    @WebResult(name = "cadastrarRegionalResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarRegionalResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.CadastrarRegionalResponse cadastrarRegional(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "cadastrarRegional", name = "cadastrarRegional", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.CadastrarRegionalRequest cadastrarRegional
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarProjetoRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarProjetoResponse")
    @WebResult(name = "cadastrarProjetoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarProjetoResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.CadastrarProjetoResponse cadastrarProjeto(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "cadastrarProjeto", name = "cadastrarProjeto", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.CadastrarProjetoRequest cadastrarProjeto
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cancelarSolicitacaoRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cancelarSolicitacaoResponse")
    @WebResult(name = "cancelarSolicitacaoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cancelarSolicitacaoResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.CancelarSolicitacaoResponse cancelarSolicitacao(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "cancelarSolicitacao", name = "cancelarSolicitacao", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.CancelarSolicitacaoRequest cancelarSolicitacao
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking//alterarStatusProjetoRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/alterarStatusProjetoResponse")
    @WebResult(name = "alterarStatusProjetoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "alterarStatusProjetoResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.AlterarStatusProjetoResponse alterarStatusProjeto(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "alterarStatusProjeto", name = "alterarStatusProjeto", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.AlterarStatusProjetoRequest alterarStatusProjeto
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarParticipanteTreinamentoRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarParticipanteTreinamentoResponse")
    @WebResult(name = "cadastrarParticipanteTreinamentoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarParticipanteTreinamentoResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.CadastrarParticipanteTreinamentoResponse cadastrarParticipanteTreinamento(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "cadastrarParticipanteTreinamento", name = "cadastrarParticipanteTreinamento", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.CadastrarParticipanteTreinamentoRequest cadastrarParticipanteTreinamento
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/sincronizarSolicitacaoRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/sincronizarSolicitacaoResponse")
    @WebResult(name = "sincronizarSolicitacaoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "sincronizarSolicitacaoResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.SincronizarSolicitacaoResponse sincronizarSolicitacao(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "sincronizarSolicitacao", name = "sincronizarSolicitacao", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.SincronizarSolicitacaoRequest sincronizarSolicitacao
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/fornecedores/services/WsSelfBooking/inserirIdentificadorIntegracaoRequest", output = "http://lemontech.com.br/selfbooking/fornecedores/services/WsSelfBooking/inserirIdentificadorIntegracaoResponse")
    @WebResult(name = "inserirIdentificadorIntegracaoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "inserirIdentificadorIntegracaoResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.InserirIdentificadorIntegracaoResponse inserirIdentificadorIntegracao(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "inserirIdentificadorIntegracao", name = "inserirIdentificadorIntegracao", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.InserirIdentificadorIntegracaoRequest inserirIdentificadorIntegracao
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/alterarStatusCentroDeCustoRequest", output = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/alterarStatusCentroDeCustoResponse")
    @WebResult(name = "alterarStatusCentroDeCustoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "alterarStatusCentroDeCustoResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.AlterarStatusCentroDeCustoResponse alterarStatusCentroDeCusto(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "alterarStatusCentroDeCusto", name = "alterarStatusCentroDeCusto", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.AlterarStatusCentroDeCustoRequest alterarStatusCentroDeCusto
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/alterarStatusRegionalRequest", output = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/alterarStatusRegionalResponse")
    @WebResult(name = "alterarStatusRegionalResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "alterarStatusRegionalResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.AlterarStatusRegionalResponse alterarStatusRegional(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "alterarStatusRegional", name = "alterarStatusRegional", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.AlterarStatusRegionalRequest alterarStatusRegional
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/contaBancariaRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/contaBancariaResponse")
    @WebResult(name = "contaBancariaResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "contaBancariaResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.ContaBancariaResponse contaBancaria(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "contaBancaria", name = "contaBancaria", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.ContaBancariaRequest contaBancaria
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/listarSubCentroDeCustoRequest", output = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/listarSubCentroDeCustoResponse")
    @WebResult(name = "listarSubCentroDeCustoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "listarSubCentroDeCustoResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.ListarSubCentroDeCustoResponse listarSubCentroDeCusto(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "listarSubCentroDeCusto", name = "listarSubCentroDeCusto", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.ListarSubCentroDeCustoRequest listarSubCentroDeCusto
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/fornecedores/services/WsSelfBooking/aprovarSolicitacaoRequest", output = "http://lemontech.com.br/selfbooking/fornecedores/services/WsSelfBooking/aprovarSolicitacaoResponse")
    @WebResult(name = "aprovarSolicitacaoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "aprovarSolicitacaoResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.AprovarSolicitacaoResponse aprovarSolicitacao(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "aprovarSolicitacao", name = "aprovarSolicitacao", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.AprovarSolicitacaoRequest aprovarSolicitacao
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/listarParametrizacaoCentroDeCustoRequest", output = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/listarParametrizacaoCentroDeCustoResponse")
    @WebResult(name = "listarParametrizacaoCentroDeCustoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "listarParametrizacaoCentroDeCustoResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.ListarParametrizacaoCentroDeCustoResponse listarParametrizacaoCentroDeCusto(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "listarParametrizacaoCentroDeCusto", name = "listarParametrizacaoCentroDeCusto", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.ListarParametrizacaoCentroDeCustoRequest listarParametrizacaoCentroDeCusto
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/liberarAdiantamentoRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/liberarAdiantamentoResponse")
    @WebResult(name = "liberarAdiantamentoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "liberarAdiantamentoResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.LiberarAdiantamentoResponse liberarAdiantamento(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "liberarAdiantamento", name = "liberarAdiantamento", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.LiberarAdiantamentoRequest liberarAdiantamento
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/importarDespesaRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/importarDespesaResponse")
    @WebResult(name = "importarDespesaResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "importarDespesaResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.ImportarDespesaResponse importarDespesa(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "importarDespesa", name = "importarDespesa", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.ImportarDespesaRequest importarDespesa
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/pesquisarVendasConsolidadoraRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/pesquisarVendasConsolidadoraResponse")
    @WebResult(name = "pesquisarVendasConsolidadoraResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "pesquisarVendasConsolidadoraResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.PesquisarVendasConsolidadoraResponse pesquisarVendasConsolidadora(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "pesquisarVendasConsolidadora", name = "pesquisarVendasConsolidadora", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.PesquisarVendasConsolidadoraRequest pesquisarVendasConsolidadora
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/atualizarBudgetRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/atualizarBudgetResponse")
    @WebResult(name = "atualizarBudgetResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "atualizarBudgetResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.AtualizarBudgetResponse atualizarBudget(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "atualizarBudget", name = "atualizarBudget", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.AtualizarBudgetRequest atualizarBudget
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/importarDelegacaoParametrizacaoCentroDeCustoRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/importarDelegacaoParametrizacaoCentroDeCustoResponse")
    @WebResult(name = "importarDelegacaoParametrizacaoCentroDeCustoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "importarDelegacaoParametrizacaoCentroDeCustoResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.ImportarDelegacaoParametrizacaoCentroDeCustoResponse importarDelegacaoParametrizacaoCentroDeCusto(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "importarDelegacaoParametrizacaoCentroDeCusto", name = "importarDelegacaoParametrizacaoCentroDeCusto", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.ImportarDelegacaoParametrizacaoCentroDeCustoRequest importarDelegacaoParametrizacaoCentroDeCusto
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/alterarStatusContaContabilRequest", output = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/alterarStatusContaContabilResponse")
    @WebResult(name = "alterarStatusContaContabilResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "alterarStatusContaContabilResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.AlterarStatusContaContabilResponse alterarStatusContaContabil(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "alterarStatusContaContabil", name = "alterarStatusContaContabil", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.AlterarStatusContaContabilRequest alterarStatusContaContabil
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/cadastrarFornecedorSourceRequest", output = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/cadastrarFornecedorSourceResponse")
    @WebResult(name = "cadastrarFornecedorSourceResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarFornecedorSourceResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.CadastrarFornecedorSourceResponse cadastrarFornecedorSource(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "cadastrarFornecedorSource", name = "cadastrarFornecedorSource", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.CadastrarFornecedorSourceRequest cadastrarFornecedorSource
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/deletarParametrizacaoCentroDeCustoRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/deletarParametrizacaoCentroDeCustoResponse")
    @WebResult(name = "deletarParametrizacaoCentroDeCustoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "deletarParametrizacaoCentroDeCustoResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.DeletarParametrizacaoCentroDeCustoResponse deletarParametrizacaoCentroDeCusto(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "deletarParametrizacaoCentroDeCusto", name = "deletarParametrizacaoCentroDeCusto", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.DeletarParametrizacaoCentroDeCustoRequest deletarParametrizacaoCentroDeCusto
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/alterarStatusFuncionarioRequest", output = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/alterarStatusFuncionarioResponse")
    @WebResult(name = "alterarStatusFuncionarioResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "alterarStatusFuncionarioResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.AlterarStatusFuncionarioResponse alterarStatusFuncionario(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "alterarStatusFuncionario", name = "alterarStatusFuncionario", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.AlterarStatusFuncionarioRequest alterarStatusFuncionario
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/listarCentroDeCustoRequest", output = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/listarCentroDeCustoResponse")
    @WebResult(name = "listarCentroDeCustoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "listarCentroDeCustoResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.ListarCentroDeCustoResponse listarCentroDeCusto(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "listarCentroDeCusto", name = "listarCentroDeCusto", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.ListarCentroDeCustoRequest listarCentroDeCusto
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarSubCentroDeCustoRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarSubCentroDeCustoResponse")
    @WebResult(name = "cadastrarSubCentroDeCustoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarSubCentroDeCustoResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.CadastrarSubCentroDeCustoResponse cadastrarSubCentroDeCusto(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "cadastrarSubCentroDeCusto", name = "cadastrarSubCentroDeCusto", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.CadastrarSubCentroDeCustoRequest cadastrarSubCentroDeCusto
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarCentroDeCustoRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarCentroDeCustoResponse")
    @WebResult(name = "cadastrarCentroDeCustoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarCentroDeCustoResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.CadastrarCentroDeCustoResponse cadastrarCentroDeCusto(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "cadastrarCentroDeCusto", name = "cadastrarCentroDeCusto", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.CadastrarCentroDeCustoRequest cadastrarCentroDeCusto
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/fornecedores/services/WsSelfBooking/inserirItemDespesaRequest", output = "http://lemontech.com.br/selfbooking/fornecedores/services/WsSelfBooking/inserirItemDespesaResponse")
    @WebResult(name = "inserirItemDespesaResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "inserirItemDespesaResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.InserirItemDespesaResponse inserirItemDespesa(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "inserirItemDespesa", name = "inserirItemDespesa", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.InserirItemDespesaRequest inserirItemDespesa
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarFuncionarioRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarFuncionarioResponse")
    @WebResult(name = "cadastrarFuncionarioResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarFuncionarioResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.CadastrarFuncionarioResponse cadastrarFuncionario(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "cadastrarFuncionario", name = "cadastrarFuncionario", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.CadastrarFuncionarioRequest cadastrarFuncionario
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/cadastrarFornecedorRequest", output = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/cadastrarFornecedorResponse")
    @WebResult(name = "cadastrarFornecedorResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarFornecedorResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.CadastrarFornecedorResponse cadastrarFornecedor(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "cadastrarFornecedor", name = "cadastrarFornecedor", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.CadastrarFornecedorRequest cadastrarFornecedor
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/pesquisarLogsAcessoRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/pesquisarLogsAcessoResponse")
    @WebResult(name = "pesquisarLogsAcessoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "pesquisarLogsAcessoResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.PesquisarLogsAcessoResponse pesquisarLogsAcesso(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "pesquisarLogsAcesso", name = "pesquisarLogsAcesso", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.PesquisarLogsAcessoRequest pesquisarLogsAcesso
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/deletarParametrizacaoViajanteRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/deletarParametrizacaoViajanteResponse")
    @WebResult(name = "deletarParametrizacaoViajanteResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "deletarParametrizacaoViajanteResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.DeletarParametrizacaoViajanteResponse deletarParametrizacaoViajante(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "deletarParametrizacaoViajante", name = "deletarParametrizacaoViajante", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.DeletarParametrizacaoViajanteRequest deletarParametrizacaoViajante
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/deletarParticipanteTreinamentoRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/deletarParticipanteTreinamentoResponse")
    @WebResult(name = "deletarParticipanteTreinamentoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "deletarParticipanteTreinamentoResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.DeletarParticipanteTreinamentoResponse deletarParticipanteTreinamento(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "deletarParticipanteTreinamento", name = "deletarParticipanteTreinamento", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.DeletarParticipanteTreinamentoRequest deletarParticipanteTreinamento
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/importarFaturaCartaoCreditoRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/importarFaturaCartaoCreditoResponse")
    @WebResult(name = "importarFaturaCartaoCreditoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "importarFaturaCartaoCreditoResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.ImportarFaturaCartaoCreditoResponse importarFaturaCartaoCredito(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "importarFaturaCartaoCredito", name = "importarFaturaCartaoCredito", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.ImportarFaturaCartaoCreditoRequest importarFaturaCartaoCredito
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/pesquisarSolicitacaoRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/pesquisarSolicitacaoResponse")
    @WebResult(name = "pesquisarSolicitacaoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "pesquisarSolicitacaoResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.PesquisarSolicitacaoResponse pesquisarSolicitacao(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "pesquisarSolicitacao", name = "pesquisarSolicitacao", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.PesquisarSolicitacaoRequest pesquisarSolicitacao
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/pesquisarContaBancariaRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/pesquisarContaBancariaResponse")
    @WebResult(name = "pesquisarContaBancariaResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "pesquisarContaBancariaResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.PesquisarContaBancariaResponse pesquisarContaBancaria(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "pesquisarContaBancaria", name = "pesquisarContaBancaria", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.PesquisarContaBancariaRequest pesquisarContaBancaria
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/consultaBilheteCiaRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/consultaBilheteCiaResponse")
    @WebResult(name = "consultaBilheteCiaResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "consultaBilheteCiaResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.ConsultaBilheteCiaResponse consultaBilheteCia(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "consultaBilheteCia", name = "consultaBilheteCia", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.ConsultaBilheteCiaRequest consultaBilheteCia
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarHoteisHomologadosRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarHoteisHomologadosResponse")
    @WebResult(name = "cadastrarHoteisHomologadosResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarHoteisHomologadosResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.CadastrarHoteisHomologadosResponse cadastrarHoteisHomologados(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "cadastrarHoteisHomologados", name = "cadastrarHoteisHomologados", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.CadastrarHoteisHomologadosRequest cadastrarHoteisHomologados
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/criarPreSolicitacaoRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/criarPreSolicitacaoResponse")
    @WebResult(name = "criarPreSolicitacaoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "criarPreSolicitacaoResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.CriarPreSolicitacaoResponse criarPreSolicitacao(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "criarPreSolicitacao", name = "criarPreSolicitacao", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.CriarPreSolicitacaoRequest criarPreSolicitacao
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/contabilizarRelatorioDespesasRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/contabilizarRelatorioDespesasResponse")
    @WebResult(name = "contabilizarRelatorioDespesasResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "contabilizarRelatorioDespesasResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.ContabilizarRelatorioDespesasResponse contabilizarRelatorioDespesas(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "contabilizarRelatorioDespesas", name = "contabilizarRelatorioDespesas", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.ContabilizarRelatorioDespesasRequest contabilizarRelatorioDespesas
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/fornecedores/services/WsSelfBooking/reprovarSolicitacaoRequest", output = "http://lemontech.com.br/selfbooking/fornecedores/services/WsSelfBooking/reprovarSolicitacaoResponse")
    @WebResult(name = "reprovarSolicitacaoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "reprovarSolicitacaoResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.ReprovarSolicitacaoResponse reprovarSolicitacao(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "reprovarSolicitacao", name = "reprovarSolicitacao", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.ReprovarSolicitacaoRequest reprovarSolicitacao
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarTreinamentoRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarTreinamentoResponse")
    @WebResult(name = "cadastrarTreinamentoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarTreinamentoResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.CadastrarTreinamentoResponse cadastrarTreinamento(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "cadastrarTreinamento", name = "cadastrarTreinamento", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.CadastrarTreinamentoRequest cadastrarTreinamento
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/pingRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/pingResponse")
    @WebResult(name = "pingResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "pingResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.PingResponse ping(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "ping", name = "ping", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.PingRequest ping
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/pesquisarFuncionarioRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/pesquisarFuncionarioResponse")
    @WebResult(name = "pesquisarFuncionarioResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "pesquisarFuncionarioResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.PesquisarFuncionarioResponse pesquisarFuncionario(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "pesquisarFuncionario", name = "pesquisarFuncionario", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.PesquisarFuncionarioRequest pesquisarFuncionario
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarContaContabilRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarContaContabilResponse")
    @WebResult(name = "cadastrarContaContabilResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarContaContabilResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.CadastrarContaContabilResponse cadastrarContaContabil(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "cadastrarContaContabil", name = "cadastrarContaContabil", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.CadastrarContaContabilRequest cadastrarContaContabil
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/alterarStatusFornecedorRequest", output = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/alterarStatusFornecedorResponse")
    @WebResult(name = "alterarStatusFornecedorResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "alterarStatusFornecedorResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.AlterarStatusFornecedorResponse alterarStatusFornecedor(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "alterarStatusFornecedor", name = "alterarStatusFornecedor", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.AlterarStatusFornecedorRequest alterarStatusFornecedor
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/pesquisarRelatorioDespesasRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/pesquisarRelatorioDespesasResponse")
    @WebResult(name = "pesquisarRelatorioDespesasResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "pesquisarRelatorioDespesasResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.PesquisarRelatorioDespesasResponse pesquisarRelatorioDespesas(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "pesquisarRelatorioDespesas", name = "pesquisarRelatorioDespesas", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.PesquisarRelatorioDespesasRequest pesquisarRelatorioDespesas
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarParametrizacaoCentroDeCustoRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/cadastrarParametrizacaoCentroDeCustoResponse")
    @WebResult(name = "cadastrarParametrizacaoCentroDeCustoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "cadastrarParametrizacaoCentroDeCustoResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.CadastrarParametrizacaoCentroDeCustoResponse cadastrarParametrizacaoCentroDeCusto(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "cadastrarParametrizacaoCentroDeCusto", name = "cadastrarParametrizacaoCentroDeCusto", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.CadastrarParametrizacaoCentroDeCustoRequest cadastrarParametrizacaoCentroDeCusto
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/deletarTreinamentoRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/deletarTreinamentoResponse")
    @WebResult(name = "deletarTreinamentoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "deletarTreinamentoResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.DeletarTreinamentoResponse deletarTreinamento(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "deletarTreinamento", name = "deletarTreinamento", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.DeletarTreinamentoRequest deletarTreinamento
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/pesquisarAdiantamentoRequest", output = "http://lemontech.com.br/selfbooking/wsselfbooking/services/WsSelfBooking/pesquisarAdiantamentoResponse")
    @WebResult(name = "pesquisarAdiantamentoResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "pesquisarAdiantamentoResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.PesquisarAdiantamentoResponse pesquisarAdiantamento(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "pesquisarAdiantamento", name = "pesquisarAdiantamento", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.PesquisarAdiantamentoRequest pesquisarAdiantamento
    );

    @WebMethod
    @Action(input = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/atrelarUsuariosRequest", output = "http://lemontech.com.br/selfbooking/fornecedores/services/WsFornecedores/atrelarUsuariosResponse")
    @WebResult(name = "atrelarUsuariosResponse", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", partName = "atrelarUsuariosResponse")
    public br.com.lemontech.selfbooking.wsselfbooking.services.response.AtrelarUsuariosResponse atrelarUsuarios(

        @WebParam(partName = "keyClient", name = "keyClient", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String keyClient,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userName,
        @WebParam(partName = "userPassword", name = "userPassword", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services", header = true)
        java.lang.String userPassword,
        @WebParam(partName = "atrelarUsuarios", name = "atrelarUsuarios", targetNamespace = "http://lemontech.com.br/selfbooking/wsselfbooking/services")
        br.com.lemontech.selfbooking.wsselfbooking.services.request.AtrelarUsuariosRequest atrelarUsuarios
    );
}
